
image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  
build: off 
  
  - java -jar ./artifacts/app-mbank.jar &

build_script:
- ./gradlew test --info  
- chmod +x gradlew
